// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJM8JytzVTSILkdBgWVaeY4nh9_R-IFn0',
    appId: '1:226574900537:ios:4292f03bf61ead32ee1ce8',
    messagingSenderId: '226574900537',
    projectId: 'fwoapp-27b94',
    storageBucket: 'fwoapp-27b94.appspot.com',
    iosBundleId: 'com.oussama.fwoapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp96hlWr6sTHijUlgEW7pYUC_KN1I1Qik',
    appId: '1:226574900537:web:329b29ab20915ec6ee1ce8',
    messagingSenderId: '226574900537',
    projectId: 'fwoapp-27b94',
    authDomain: 'fwoapp-27b94.firebaseapp.com',
    storageBucket: 'fwoapp-27b94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWfEkH8_Jhx92gW7-jwo8hkOcT-VCJ7-4',
    appId: '1:226574900537:android:2e8529fad16d4805ee1ce8',
    messagingSenderId: '226574900537',
    projectId: 'fwoapp-27b94',
    storageBucket: 'fwoapp-27b94.appspot.com',
  );

}